config/routes.rb
Rails.application.routes.draw do
  root 'matches#index'
  resources :matches, only: [:show, :index]
  devise_for :users
  namespace :admin do
      resources :countries
      resources :matches
      root to: "matches#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    validates_presence_of :name
    def matches
        Match.matches(self.id)        
    end
end

app/models/match.rb
class Match < ApplicationRecord
    validates_presence_of :date, :group, :phase

    belongs_to :country_1, :class_name => 'Country', :foreign_key => "country_1_id"
    belongs_to :country_2, :class_name => 'Country', :foreign_key => "country_2_id"

    scope :matches, -> (id) { where "country_1_id = ? OR country_2_id = ?", id, id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!

    def records_per_page
      params[:per_page] || 15
    end
  end
end

app/controllers/admin/countries_controller.rb
module Admin
  class CountriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Country.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Country.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/matches_controller.rb
module Admin
  class MatchesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Match.
    #   page(params[:page]).
    #   per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Match.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def after_sign_out_path_for(resource_or_scope)
        root_path
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all.includes(:country_1, :country_2)
  end

  def show
    @match = Match.find(params[:id])
  end

  def create
    match = Match.create(match_params)
    redirect_to matches_path
  end

  def update
    @match = Match.find(params[:id])
    @match.update(match_params)
    redirect_to matches_path(@match)
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    redirect_to matches_path
  end

  private

  def match_params
    params.require(:match).permit(:date, :phase, :group, :score_1, :score2, :country_1_id, :country_2_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/admin/application/_navigation.html.erb
<nav class="navigation" role="navigation">
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      [namespace, resource_index_route_key(resource)],
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) %>
  <% end %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PencaCA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/matches/index.html.erb
<h1>Penca Copa América</h1>
<br>
<div class="container">
    <h5 class="font-weight-bold">Partidos</h5>
    <div class="row">
        <% @matches.each do |match| %>
                <div class="col-3 border m-2"> 
                <%= link_to match_path(match.id), class: 'link_color' do %>
                    <p class="font-weight-bold text-center"><%= match.country_1.name %>  vs <%= match.country_2.name %></p>
                    <p class="text-center small"> <%= match.date.strftime("%H:%Mhs - %d/%m/%Y") %> </p> 
                <% end %>
                </div>
        <% end %>
    </div>
</div>

app/views/matches/show.html.erb
<h4><%= @match.country_1.name %>  vs <%= @match.country_2.name %></h4>
<p> <%= @match.date.strftime("%H:%Mhs - %d/%m/%Y") %> </p> 